---

- name: test
  hosts: all
  tasks:
  - name: ping
    ansible.builtin.ping:
    register: result
    
  - name: ping result
    debug:
      var: result
    
  - name: run if ping successful
    debug:
      msg: "Ping was successful"
    when: result.changed == false
